version: "3.7"

services:
    db:
        image: mongo
        container_name: db
        restart: always
    akkount:
        container_name: akkount
        image: node:lts-alpine3.13
        restart: always
        ports:
            - 127.0.0.1:3000:80
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        command: "yarn start"
