version: "3.7"

services:
    db:
        image: postgres:alpine
        container_name: db
        restart: always
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - 127.0.0.1:5432:5432
