version: "3.7"

services:
    db:
        image: postgres:alpine
        container_name: db
        restart: always
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - 127.0.0.1:5432:5432
    pgadmin:
        image: dpage/pgadmin4:5.4
        container_name: pgadmin
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin@example.com
            - PGADMIN_DEFAULT_PASSWORD=password
            - PGADMIN_CONFIG_SHOW_GRAVATAR_IMAGE=False
        volumes:
            - ./config/pgadmin/servers.json:/pgadmin4/servers.json
        ports:
            - 127.0.0.1:8080:80
