version: "3.7"

services:
    db:
        image: postgres:alpine
        container_name: db
        restart: always
        environment:
            - POSTGRES_PASSWORD=password
        networks:
            - db

networks:
    db:
        name: interossea-db
